### PR TITLE
Update for new rabbitmq key

### PR DESCRIPTION
**Pull request by jpic**
It has changed upstream.

http://www.rabbitmq.com/news.html#2016-05-25T18:00:00+03:00

### CODE REVIEW

**Comment by jpic** [comment]
Note: this fix the current breakage when using the role. This fix is critical.

**Comment by LouisVN** [comment]
+1 for this. It fixed the issue on our side.

**Comment by jpic** [comment]
Thanks @alexey-medvedchikov , nice role BTW :guitar:

**Comment by alexey-medvedchikov** [comment]
@jpic Actually, this role is almos abandoned and is here only for compatibility purpose. You should use nice one from Openstack Ansible https://git.openstack.org/cgit/openstack/openstack-ansible-rabbitmq_server/

**Comment by jpic** [comment]
Thanks @alexey-medvedchikov, good to know, but the openstack role is not in galaxy. Perhaps we could setup this repo to be a pulling mirror of the github one ? Dunno if this feature is available in github, I know it is in gitlab though.

**Comment by alexey-medvedchikov** [comment]
@jpic galaxy truly sucks, it's unavailable too often, it's slow. We're abandoned using it, just use git.

**Pull request merged**
